### ISSUE TITLE
Doesn't seem to support rpc://

### ISSUE THREAD

**Issue by romech** [clokep/celery-batches#24]
Hi,

Thanks for nice library! I have a problem with rpc as results backend, while [file-system backend](https://docs.celeryproject.org/en/stable/userguide/configuration.html#file-system-backend-settings) works fine. I couldn't make rpc work even with some basic return values. Here's my minimal example:

**server.py**
```python
import logging

from celery import Celery
from celery_batches import Batches


app = Celery('example',
             backend='rpc://',
            #  backend='file://.celery_store',
             broker='amqp://guest@localhost//',
)

@app.task(base=Batches, flush_every=3, flush_interval=0.1)
def process(inputs=None):
    logging.info('Received {} tasks'.format(len(inputs)))
    for inp in inputs:
        app.backend.mark_as_done(inp.id, 'ok')
```

**client.py**
```python
from server import process


if __name__ == '__main__':
    tasks = [process.delay() for _ in range(3)]

    for task in tasks:
        output = task.get(timeout=10)
```

The client script fails with `celery.exceptions.TimeoutError: The operation timed out.`.

Library versions:
```
celery==5.0.5
celery-batches==0.4
```

**Comment by clokep** [comment]
Just to double check -- you're sure the backend works OK with normal tasks?

**Comment by romech** [comment]
@clokep yes, it does

**Comment by clokep** [comment]
To be honest I haven't used that much (and I think do not believe there's any unit tests). Maybe there's probably something weird with not ensuring the connection is open first? I'll try to look soon.

**Comment by clokep** [comment]
So, RPC is weird. I had to go back to a post I wrote a long time ago about how this all works to figure it out.

This is breaking because RPC stores multiple results in the same queue, so the task ID actually gets encoded into the message.

Calling `app.backend.mark_as_done(inp.id, 'ok')` causes it to store the result...nowhere because the RPC backend thinks the queue isn't a thing (it does seem to create a queue with the task ID though, which is wrong).

I'm not sure there's a reasonable workaround, but it seems that our custom `Request` class is wrong in some way or another.

**Comment by clokep** [comment]
The following patch *might* fix the issue, but I would need to remind myself why `SimpleRequest` exists:

```diff
diff --git a/celery_batches/__init__.py b/celery_batches/__init__.py
index dcfc30e..e2402db 100644
--- a/celery_batches/__init__.py
+++ b/celery_batches/__init__.py
@@ -304,8 +304,7 @@ class Batches(Task):
         return super(Batches, self).apply(([request],), {}, *_args, **_kwargs)
 
     def flush(self, requests):
-        return self.apply_buffer(requests, ([SimpleRequest.from_request(r)
-                                             for r in requests],))
+        return self.apply_buffer(requests, (requests,))
 
     def _do_flush(self):
         logger.debug('Batches: Wake-up to flush buffer...')
```

Would be curious for you to give it a try and see if it fixes the problem for you though!

**Comment by clokep** [comment]
Oh, you'd also need to update the call to save the result to send the task into it:

`app.backend.mark_as_done(inp.id, 'ok', request=inp)`

**Comment by romech** [comment]
Thanks for getting back to this!

I'm getting an exception:
```
[2021-05-20 18:28:19,323: ERROR/MainProcess] Error in timer: TypeError("cannot pickle '_thread.lock' object")
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 145, in fire_timers
    entry()
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/kombu/asynchronous/timer.py", line 130, in _reschedules
    return fun(*args, **kwargs)
  File "/home/user/sample_project/celery_batches/__init__.py", line 315, in _do_flush
    self.flush(requests)
  File "/home/user/sample_project/celery_batches/__init__.py", line 306, in flush
    return self.apply_buffer(requests, (requests,))
  File "/home/user/sample_project/celery_batches/__init__.py", line 333, in apply_buffer
    return self._pool.apply_async(
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/celery/concurrency/base.py", line 155, in apply_async
    return self.on_apply(target, args, kwargs,
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/billiard/pool.py", line 1530, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
  File "/home/user/anaconda3/envs/nn/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 885, in send_job
    body = dumps(tup, protocol=protocol)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by clokep** [comment]
Right, so I guess `SimpleRequest` really does need to get pickled. (I was testing with a solo pool, I'm guessing you're using prefork, which makes sense for production.)

So this will need more work to fix, unfortunately.

**Comment by clokep** [comment]
@romech Does #30 fix this issue for you? It worked in my testing, but struggling with some unit tests for it. 😄

**Comment by romech** [comment]
Yay, it works!

**Comment by clokep** [comment]
Awesome! I'll try to do a release next week since we need one for celery 5.1 anyway.

**Comment by clokep** [comment]
I pushed v0.5 which includes the fix for this. Thanks for reporting / testing!
