### ISSUE TITLE
Application context not available when using Flask integration recipe

### ISSUE THREAD

**Issue by jimleroyer** [clokep/celery-batches#35]
Is there any recommendation on how to properly wire up celery-batches with Flask when an application is using the integration recipe [as described under this URL](https://flask.palletsprojects.com/en/2.0.x/appcontext/)? [Our application uses this recipe](https://github.com/cds-snc/notification-api/blob/master/app/celery/celery.py#L14-L34) by [subtasking the Celery Task class](https://stackoverflow.com/a/51254227/647641) but then, so when trying to integration with celery-batches and specifying Base as an argument to define the task implementation to use, it bypasses the wiring.

**Comment by clokep** [comment]
I haven't attempted to use Celery (or celery-batches) with Flask, so I don't have any particular recommendations.

> so when trying to integration with celery-batches and specifying Base as an argument to define the task implementation to use, it bypasses the wiring.

I'm not 100% sure what this means, do you have an example? It is quite possible that celery-batches doesn't work well with class-based tasks, as it isn't really a pattern I see often (or recommend, personally). Sticking with function based tasks should work. Is there a particular reason you're using class-based tasks?

**Comment by clokep** [comment]
Closing due to lack of response.

**Comment by jimleroyer** [comment]
Sorry for not replying, I appreciate your answer. We ended up using a custom in-house solution.

**Comment by clokep** [comment]
No problem! Glad you got something working. 👍
