### ISSUE TITLE
Make docs more prominent (GitHub, pypi, and README)

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#41]
The only place I've found linking to docs was the badge. Personally I've linked that in my own projects to RTD/github action build status.

Link to this in pypi, github, and README (beyond just the badge): https://celery-batches.readthedocs.io/en/latest/

**Comment by clokep** [comment]
I put up #43 to update the metadata for PyPI, not sure why I never did that. Thanks!

The README could definitely have some more info in it (and some of what's in the README really should be in the documentation...)

I'm not really sure what you mean to link to it from GitHub though -- as far as I know there isn't a spot to link to documentation.

**Comment by tony** [comment]
@clokep One nice place to link to docs is here:

![image](https://user-images.githubusercontent.com/26336/155223403-b50da4ab-8d53-4f06-9627-e8ceaa353e02.png)

Example in https://github.com/tmux-python/tmuxp:
![image](https://user-images.githubusercontent.com/26336/155223433-a4809b6a-722b-400f-a2b7-b8b6d2c2b07a.png)

You can also add tags there

**Comment by tony** [comment]
@clokep Can you look at filling these out? It's hard to notice where the docs are still

**Comment by clokep** [comment]
It is on my to do list, yep.

**Comment by clokep** [comment]
This is done.

**Comment by tony** [comment]
@clokep massively easier for me now

hopefully github search brings this up to bring in more foot traffic
