### ISSUE TITLE
`poetry` package management?

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#48]
I use this on a few projects:
https://github.com/tmux-python/tmuxp/blob/master/pyproject.toml, https://github.com/tmux-python/libtmux/blob/master/pyproject.toml, https://github.com/cihai/unihan-etl/blob/master/pyproject.toml

- easy to get into virtualenv, `poetry shell`
- `poetry install`
- `poetry publish` to make wheel / sdist and push to pypi
- I believe it works with RTD, but not sure since I moved to s3/cloudfront

**Comment by clokep** [comment]
I don't have interest in switching to poetry at this time. If the Python ecosystem settles on a single solution different from setuptools than I'll be happy to switch, but there's too much churn right now to worry about it IMO.

**Comment by tony** [comment]
What's fascinating is pypa uses pipenv: https://github.com/pypa/pipenv, it's getting users again

Nearly equal downloads:
- https://pypistats.org/packages/pipenv vs https://pypistats.org/packages/poetry

What it needed, down the line, perhaps is the projects to merge
