### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#54]
Carried forward from https://github.com/clokep/celery-batches/issues/42#issuecomment-1045206140 by @clokep

- Keep in `examples/`
- Back via pytest to automatically detect breakages via CI
- Copy-paste friendly
- #53: Potentially show interoperation with other base classes

**Comment by clokep** [comment]
I did some of this, but did not setup automated testing for it. That's a bit harder to do since you have to configure the brokers and backends such. It is probably doable with some effort though.

**Comment by tony** [comment]
@clokep Awesome!

If I have an idea about the automated testing I will PR it
