### ISSUE TITLE
Multiple tasks issue

### ISSUE THREAD

**Issue by bennylin77** [clokep/celery-batches#73]
I try to run in multiple tasks but every time running for a while the batch stop functioning only process one task per time.

Example:

```
@celery.task(name="create_task_a", base=Batches, flush_every=20, flush_interval=1.5)
def create_task_a(): 

@celery.task(name="create_task_b", base=Batches, flush_every=20, flush_interval=1.5)
def create_task_b(): 
```

If i only run create_task_a, it is good. Celery can process task in a batch(20). 
But if i run `create_task_a`  and `create_task_b` at same time, it always be good at the beginning and stop batch process after a few batches

iteration: 1
[create_task_a, create_task_a...... 20 in total]
iteration: 2
[create_task_a, create_task_a......20 in total]
iteration: 3
[create_task_b create_task_b......20 in total]
iteration: 4
[create_task_a create_task_a......20 in total]
..... after  5-6 iteration
iteration:
[create_task_a create_task_a......8 in total]
[create_task_b create_task_b......6 in total]
[create_task_b create_task_b......3 in total]
..... after 15-20 iteration
[create_task_a]
[create_task_a]
[create_task_b]
[create_task_b]
[create_task_a]
[create_task_b]

how can i fix the issue? thanks in advance

**Comment by clokep** [comment]
What version of celery and celery-batches are you running?

Mostly it sounds like it might not be pulling tasks quickly enough from the queue. Does this still happen if you raise `flush_interval`?

**Comment by bennylin77** [comment]
@clokep celery 5.2.3, celery-batches 0.7
Even I increase the `interval` the issue is still there

**Comment by bennylin77** [comment]
once i change worker_prefetch_multiplier to zero the issue is gone, but comes another issue. i will create another ticket for that. thanks @clokep
