### ISSUE TITLE
Unable to install with celery 5.3.1

### ISSUE THREAD

**Issue by mhsparks** [clokep/celery-batches#79]
Thanks for merging #75 but I'm not able to install with celery 5.3.1, presumably because of this line 

https://github.com/clokep/celery-batches/blob/e7e3f2c81c9a2c12e5133dc286f2ba08b15c64cb/setup.cfg#L38

Does the 5.3 need changing to 5.4?

The error when trying to run `pip-compile` is:

```
There are incompatible versions in the resolved dependencies:
  celery==5.3.1 from https://files.pythonhosted.org/packages/18/b9/cb8d519ea0094b9b8fe7480225c14937517729f8ec927643dc7379904f64/celery-5.3.1-py3-none-any.whl (from -r requirements.in (line 11))
  celery<5.3,>=5.0 (from celery-batches==0.8->-r requirements.in (line 12))
```

**Comment by stegayet** [comment]
https://github.com/clokep/celery-batches/pull/80 will solve the issue, my bad :smile:

**Comment by clokep** [comment]
Good-catch. I'm not sure why CI didn't catch this though.

**Comment by clokep** [comment]
Hopefully 0.8.1 fixes this. 👍
