### ISSUE TITLE
Support for celery 5.4

### ISSUE THREAD

**Issue by bufke** [clokep/celery-batches#87]
Hello, celery 5.4 is released. The setup.py requires <5.4. Would you like any help testing/supporting 5.4?

**Comment by bufke** [comment]
My bad @clokep , I updated the title. 

@tony I'm sure that's a touchy subject that is up to the maintainers. I personally agree with you, that it discourages participation testing, by raising the level of effort to test, more than it helps. Poetry not allowing overrides, the way say npm does, is IMO problematic and more at fault.

**Comment by clokep** [comment]
The change to support this *should* just be updating the bounds & adding it to CI.

It looks like tests might be broken on Python 3.11 right now though for some reason.

**Comment by clokep** [comment]
I pushed 0.9 which supports celery 5.4, sorry for the delay there.
