### ISSUE TITLE
Remove upper bounds on version constraints

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#88]
@clokep Hi!

Can you please remove upper bounds on version constraints for `celery` and publish a release? 

This is affecting my verifying compatibility of `celery-batches` with `celery` 5.4.0+ (see #87). In this case, celery is a transitive dependency blocking a larger update. I expect others are similarly bottlenecked.

Rationale:
- Removing the upper bound does not imply compatibility
- Those who run into any issues can report a bug or a open pull request, rather than the package not installing.
- Package managers, e.g. `poetry`, are enforcing these upper bounds strictly, inhibiting ability to test basic functionality
  - There may not necessarily be a breakage. In which case downstream users are blocked unnecessarily.

**Comment by clokep** [comment]
As mentioned in the pull request -- I'm not comfortable with this change. Celery has broken backwards compatibility in the past.
